In [1]:
# Data processing
import pandas as pd
import numpy as np

# Train test split
from sklearn.model_selection import train_test_split

# Modeling
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification

# Import accuracy_score to check performance
from sklearn.metrics import accuracy_score

Importing the data

In [2]:
data=pd.read_csv("labeled_data_new.csv",names=['count','hate_speech','offensive_language','neither','class','tweet'])

In [3]:
data.head()







count  hate_speech  offensive_language  neither  class  \
0  count  hate_speech  offensive_language  neither  class   
1      3            0                   0        3      2   
2      3            0                   3        0      1   
3      3            0                   3        0      1   
4      3            0                   2        1      1   

                                               tweet  
0                                              tweet  
1     as a woman you shouldnt complain about clea...  
2     boy dats coldtyga dwn bad for cuffin dat ho...  
3     dawg   you ever fuck a bitch and she start ...  
4                             she look like a tranny

In [4]:
# Split data into train and test sets
train_text, test_text, train_labels, test_labels = train_test_split(data['offensive_language'], data['offensive_language'], test_size=.2)


In [5]:
# aplit to train and test
X_train, X_test, y_train, y_test = train_test_split(data['offensive_language'], data['offensive_language'], test_size=.2)


In [6]:
# Convert X_train and X_test to lists of strings if they are not already
# Tokenizer from a pretrained model
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
#should be the same name from hugging face library

# Tokenize the reviews
tokenized_data_train = tokenizer(X_train.to_list(), return_tensors="np", padding=True)
tokenized_data_test = tokenizer(X_test.to_list(), return_tensors="np", padding=True)

# Labels are one-dimensional numpy or tensorflow array of integers
labels_train = np.array(y_train)
labels_test = np.array(y_test)

# Tokenized ids
print(tokenized_data_train["input_ids"][0])

[101 124 102   0   0]


In [7]:
model = TFAutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [8]:
# Loss
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

# Compile model
model.compile(optimizer=Adam(5e-6), loss=loss, metrics=['accuracy'])

In [10]:
model.fit(dict(tokenized_data_train),
          labels_train,
          validation_data=(dict(tokenized_data_test), labels_test),
          batch_size=4,
          epochs=2)

Epoch 1/2


2023-12-27 22:01:55.482554: W tensorflow/core/framework/op_kernel.cc:1816] OP_REQUIRES failed at cast_op.cc:122 : UNIMPLEMENTED: Cast string to float is not supported


UnimplementedError: Graph execution error:

Detected at node Cast_1 defined at (most recent call last):
  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/runpy.py", line 197, in _run_module_as_main

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/runpy.py", line 87, in _run_code

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/ipykernel_launcher.py", line 16, in <module>

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 677, in start

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 199, in start

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/asyncio/base_events.py", line 596, in run_forever

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/asyncio/events.py", line 80, in _run

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 471, in dispatch_queue

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 460, in process_one

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 367, in dispatch_shell

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 662, in execute_request

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 360, in do_execute

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 532, in run_cell

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code

  File "/var/folders/wd/fzj4fynx73l9ts0177tlxx2h0000gn/T/ipykernel_7659/2841761837.py", line 1, in <module>

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/keras/src/engine/training.py", line 1807, in fit

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/keras/src/engine/training.py", line 1401, in train_function

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/keras/src/engine/training.py", line 1384, in step_function

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/keras/src/engine/training.py", line 1373, in run_step

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/transformers/modeling_tf_utils.py", line 1679, in train_step

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/keras/src/engine/compile_utils.py", line 620, in update_state

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/keras/src/utils/metrics_utils.py", line 77, in decorated

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/keras/src/metrics/base_metric.py", line 140, in update_state_fn

  File "/Users/davidrothschild/Library/r-miniconda-arm64/lib/python3.9/site-packages/keras/src/metrics/base_metric.py", line 708, in update_state

Cast string to float is not supported
	 [[{{node Cast_1}}]] [Op:__inference_train_function_36218]

In [11]:
y_test_predict = model.predict(dict(tokenized_data_test))['logits']

# First 5 predictions
y_test_predict[:5]

155/155 [==============================] - 11s 68ms/step


array([[-0.57059675, -0.42047772],
       [-0.57059675, -0.42047772],
       [-0.5471485 , -0.40635556],
       [-0.51642346, -0.42630106],
       [-0.5067047 , -0.4999436 ]], dtype=float32)

In [12]:
# Predicted probabilities
y_test_probabilities = tf.nn.softmax(y_test_predict)

# First 5 predicted probabilities
y_test_probabilities[:5]

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0.46254054, 0.53745943],
       [0.46254054, 0.53745943],
       [0.46485978, 0.5351402 ],
       [0.4774846 , 0.52251536],
       [0.49830976, 0.50169027]], dtype=float32)>

In [13]:
# Predicted label
y_test_class_preds = np.argmax(y_test_probabilities, axis=1)

# First 5 predicted labels
y_test_class_preds[:5]

array([1, 1, 1, 1, 1])

In [14]:
accuracy_score(y_test_class_preds, y_test)

0.0